namespace FastFile.ModelsOLD.Assets.Weapons.Enums;

public enum ImpactType
{
    IMPACT_TYPE_NONE = 0,
    IMPACT_TYPE_BULLET_SMALL = 1,
    IMPACT_TYPE_BULLET_LARGE = 2,
    IMPACT_TYPE_BULLET_AP = 3,
    IMPACT_TYPE_SHOTGUN_FMJ = 4,
    IMPACT_TYPE_SHOTGUN = 5,
    IMPACT_TYPE_GRENADE_BOUNCE = 7,
    IMPACT_TYPE_GRENADE_EXPLODE = 8,
    IMPACT_TYPE_ROCKET_EXPLODE = 9,
    IMPACT_TYPE_PROJECTILE_DUD = 10,
    IMPACT_TYPE_MAX
};